package fx.fx.exceptions;

/**
 * Thrown if the currency pair does not exist, e.g. AAABBB
 */
public class CurrencyPairSyntaxException extends Exception {
    
    //autogenerated
	private static final long serialVersionUID = 2338692337840372922L;

	public CurrencyPairSyntaxException(){
        
    }
}
