package fx.fx.exceptions;

/**
 * Thrown if a currency pair's length is not 6.
 */
public class CurrencyPairLengthException extends Exception {

    //autogenerated
    private static final long serialVersionUID = -8411151981393454517L;

    public CurrencyPairLengthException() {
    }

}
