package fx.fx.exceptions;

/**
 * Thrown if the amount is negative.
 */
public class NegativeAmountException extends Exception {

    //autogenerated
	private static final long serialVersionUID = 866509498564988200L;

	public NegativeAmountException(){
        
    }
}
